### ISSUE TITLE
Add underline on links 

### ISSUE THREAD

**Issue by JoseRenan** [calluswhatyouwant/musicritic#130]
**Is your feature request related to a problem? Please describe.**

Some users didn't recognized that the artist name and album name are links in this card:

![image](https://user-images.githubusercontent.com/11728746/110250299-62b86280-7f59-11eb-9002-b95b145f2341.png)

So maybe add underlines on them, to make it recognizable

**Comment by 96RadhikaJadhav** [comment]
@JoseRenan  can I work on it?

**Comment by JoseRenan** [comment]
@96RadhikaJadhav Yes!! I will assign the issue to you :smile:
