### ISSUE TITLE
Implement login with social networks

### ISSUE THREAD

**Issue by JoseRenan** [calluswhatyouwant/musicritic#24]
Implement the login with social networks (Facebook and Twitter) using firebase.

**Comment by JoseRenan** [comment]
Testing bot

**Comment by thayannevls** [comment]
@JoseRenan Why use other social networks if spotify is needed to musicritic work?

**Comment by JoseRenan** [comment]
The main idea is to make possible to the user make reviews without connecting with Spotify account but connecting he will have access to more features like suggestions of music to review and improve the reviews feed on the main page

**Comment by JoseRenan** [comment]
Do you think it makes sense? The is is to make musicritic available to people who don't use Spotify too

**Comment by thayannevls** [comment]
Oh! Now I understand. It makes sense :)

**Comment by JRobsonJr** [comment]
I discussed with @JoseRenan about this and we agreed that for now, we'll focus on the application depending on a Spotify account. We'll consider that Musicritic is an app for Spotify users first, and we might in the future come back to this issue.

**Comment by JRobsonJr** [comment]
Leaving it open so we don't lose track of it :v

**Comment by JoseRenan** [comment]
We decided to keep the login with Spotify as the only way to use musicritic for now, just for simplification since we integrated the Spotify login with firebase. If we add support to other streaming platforms in the future, we implement the login with those platforms too.

So, we are closing this issue :smile:

**Comment by JoseRenan** [comment]
PS: The ideia is that not logged users could use musicritic, but to add reviews and etc, only logged users (and for now, logged with a spotify account)
