### ISSUE TITLE
Implement Spotify Logout 

### ISSUE THREAD

**Issue by thayannevls** [calluswhatyouwant/musicritic#48]
**Is your feature request related to a problem? Please describe.**
Currently the user can't logout in the system or switch accounts.

**Describe the solution you'd like**
A Option to logout of the system.

**Describe alternatives you've considered**
A button of *logout* next to the *Home* button.

**Comment by JoseRenan** [comment]
In order to implement this, we just need to add a button that clears the localStorage and call firebase.logout()

**Comment by emys-alb** [comment]
Can i take this issue?
