### ISSUE TITLE
Remove components using deprecated lifecycle

### ISSUE THREAD

**Issue by JoseRenan** [calluswhatyouwant/musicritic#66]
**Describe the bug**
componentWillReceiveProps and componentWillMount are being deprecated by react, we actually have some components and a dependency (Formik) which uses those lifecycles. We need to refactor those components and update the Formik version

**Comment by lucasmedeiros** [comment]
Posso pegar? :eyes:

**Comment by JoseRenan** [comment]
Todo seu
