### ISSUE TITLE
Create endpoint for adding track reviews

### ISSUE THREAD

**Issue by JRobsonJr** [calluswhatyouwant/musicritic#71]
Create endpoint on backend to add reviews to track.

endpoint:

`/tracks/{track id on spotify}/reviews`

- POST
   1. It will receive a JSON with the format:
    ```json
   {
     "user": "userId",
     "track": "id of the track on spotify",
     "rating": 4.5,
     "review": "[OPTIONAL OBJECT TO BE DEFINED]"
    }
   ```
   1. Store it in a collection "reviews/tracks" (there is a concept of subcollection on firestore) using the [firebase cloud firestore](https://firebase.google.com/docs/firestore), we already have an example using the cloud firestore [here](https://github.com/calluswhatyouwant/musicritic/blob/master/server/src/users/userCollections.js)
   1. Return the review JSON with its id

if the #69 is already done, this endpoint must be protected to be called only by logged users

**Comment by lucasmedeiros** [comment]
@JRobsonJr I would like to take this one, could you give more context on it, please? :heart:

**Comment by JRobsonJr** [comment]
@lucasmedeiros sorry, this one is one of our tasks for a university project :cry: I'll add a label to signal this so that people don't get confused in the future. But feel free to help with the ones tagged with _hacktoberfest_! :pleading_face:
